"""init schema

Revision ID: b42c5f56b69b
Revises: 
Create Date: 2026-01-17 09:18:06.953155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b42c5f56b69b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_user_email'), 'user_user', ['email'], unique=True)
    op.create_table('label_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_label_owner_name')
    )
    op.create_index(op.f('ix_label_label_name'), 'label_label', ['name'], unique=False)
    op.create_index(op.f('ix_label_label_owner_id'), 'label_label', ['owner_id'], unique=False)
    op.create_table('note_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_note_owner_id'), 'note_note', ['owner_id'], unique=False)
    op.create_table('label_notelabellink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['label_label.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['note_note.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', 'label_id', name='uq_note_label_link')
    )
    op.create_index(op.f('ix_label_notelabellink_label_id'), 'label_notelabellink', ['label_id'], unique=False)
    op.create_index(op.f('ix_label_notelabellink_note_id'), 'label_notelabellink', ['note_id'], unique=False)
    op.create_table('share_labelshare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('READ', 'EDIT', name='sharerole'), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['label_label.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label_id', 'user_id', name='uq_label_user')
    )
    op.create_index(op.f('ix_share_labelshare_label_id'), 'share_labelshare', ['label_id'], unique=False)
    op.create_index(op.f('ix_share_labelshare_user_id'), 'share_labelshare', ['user_id'], unique=False)
    op.create_table('share_noteshare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('READ', 'EDIT', name='sharerole'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note_note.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', 'user_id', name='uq_note_user')
    )
    op.create_index(op.f('ix_share_noteshare_note_id'), 'share_noteshare', ['note_id'], unique=False)
    op.create_index(op.f('ix_share_noteshare_user_id'), 'share_noteshare', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_noteshare_user_id'), table_name='share_noteshare')
    op.drop_index(op.f('ix_share_noteshare_note_id'), table_name='share_noteshare')
    op.drop_table('share_noteshare')
    op.drop_index(op.f('ix_share_labelshare_user_id'), table_name='share_labelshare')
    op.drop_index(op.f('ix_share_labelshare_label_id'), table_name='share_labelshare')
    op.drop_table('share_labelshare')
    op.drop_index(op.f('ix_label_notelabellink_note_id'), table_name='label_notelabellink')
    op.drop_index(op.f('ix_label_notelabellink_label_id'), table_name='label_notelabellink')
    op.drop_table('label_notelabellink')
    op.drop_index(op.f('ix_note_note_owner_id'), table_name='note_note')
    op.drop_table('note_note')
    op.drop_index(op.f('ix_label_label_owner_id'), table_name='label_label')
    op.drop_index(op.f('ix_label_label_name'), table_name='label_label')
    op.drop_table('label_label')
    op.drop_index(op.f('ix_user_user_email'), table_name='user_user')
    op.drop_table('user_user')
    # ### end Alembic commands ###
